services:
  postgres:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.postgres
    container_name: postgres
    ports:
      - '5434:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sunil -d postgresdb -h localhost || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s  # Wait for a while before running the first health check

  auth-rest-api:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.auth-rest-api
    ports:
      - '8080:8080'
    container_name: auth-rest-api
    depends_on:
      postgres:
        condition: service_healthy
